#!/bin/bash
# ==============================================================================
# Version       : 0.1
# Date          : 2017/03/30
# Last updated  : 2017/03/30
# Autor         : Alexandre Bray
# Information   : support@opendoc.net 
# GIT URL       : https://github.com/opendocnet/elk/blob/master/check_events_logstash_shipper
# GIT REVISION  : 26
# Revision :
#   0.1 : first version (rev 26)
# ==============================================================================

# ------------------------------------------------------------------------------
# VARIABLES
# ------------------------------------------------------------------------------
Timeout=10
BinJq="/home/nagios/plugins/tools/jq"
Tmp="/run/shm"
NewTime="$(date +%s)"

# ------------------------------------------------------------------------------
# FUNCTIONS 
# ------------------------------------------------------------------------------
#> Print usage
fct_usage () {
    echo "Usage: `basename $0` -H <host> -t <timeout>"
    echo ""
    echo "  -H  : logstash host"
    echo "  -t  : timeout of request (default 10s)"
    echo "  -h  : show help"
    echo ""
    exit 2
}

#> Process command line options
fct_doopts () {
    IFS=$'\n'
    for args in $(echo -e "$(echo " $@" |sed 's/ -/\\n/g')"); do
        Opt="$(echo "${args}" |cut -d " " -f1)"
        ArgOpt="$(echo "${args}" |cut -d " " -f2-99 )"
        
        case "${Opt}" in
            "H"|"host")         Host="${ArgOpt}";;
            "t"|"timeout")      Timeout="${ArgOpt}";;
            *)                  fct_usage ;;
        esac
     
    done
}


fct_logstash_events () {
    
    BufferLogstashEvents="${Tmp}/buffer_events_logstash_shipper_${Host}"
    
    DataLogstashShipper=$(curl --connect-timeout ${Timeout} "http://${Host}:9620/_node/stats/pipeline?pretty=true" 2>/dev/null)
    if (( $? != 0 )) ; then
         
        echo "CRITICAL : The Logstash shipper API does not respond"
        exit 2
        
    fi
    
    NewEventLostashShipperIn=$(echo -e "${DataLogstashShipper}" |${BinJq} '.pipeline.events.in' |sed 's/null/0/')
    NewEventLostashShipperOut=$(echo -e "${DataLogstashShipper}" |${BinJq} '.pipeline.events.out' |sed 's/null/0/')
    
    if ! test -s ${BufferLogstashEvents}; then
        
        echo "${NewTime};${NewEventLostashShipperIn};${NewEventLostashShipperOut}" > ${BufferLogstashEvents}
        echo "Buffer in progress..."
        exit 3
        
    fi
    
    Time=$(( ${NewTime} - $(cat ${BufferLogstashEvents} |awk -F ";" '{print $1}') ))
    EventLostashShipperIn=$(( $(( ${NewEventLostashShipperIn} - $(cat ${BufferLogstashEvents} |awk -F ";" '{print $2}') )) / ${Time}))
    EventLostashShipperOut=$(( $(( ${NewEventLostashShipperOut} - $(cat ${BufferLogstashEvents} |awk -F ";" '{print $3}') )) / ${Time}))
    
    if (( ${EventLostashShipperIn} < 0 || ${EventLostashShipperOut} < 0 )); then
        rm ${BufferLogstashEvents}
        echo "Reset buffer"
        exit 3
    fi
    
    echo "${NewTime};${NewEventLostashShipperIn};${NewEventLostashShipperOut}" > ${BufferLogstashEvents}

    DelayLogstashShipper=$(( ${EventLostashShipperIn} - ${EventLostashShipperOut} ))
    
    if (( ${DelayLogstashShipper} != 0  )); then
    
        echo "CRITICAL : IN ${EventLostashShipperIn}/s OUT ${EventLostashShipperOut}/s DELAY ${DelayLogstashShipper}. Please see Redis status |in=${EventLostashShipperIn} out=${EventLostashShipperOut} delay=${DelayLogstashShipper}"
        exit 2
        
    else
        
        echo "OK : IN ${EventLostashShipperIn}/s OUT ${EventLostashShipperOut}/s DELAY ${DelayLogstashShipper} |in=${EventLostashShipperIn} out=${EventLostashShipperOut} delay=${DelayLogstashShipper}"
        exit 0
        
    fi

}

#-------------------------------------------------------------------------------
# MAIN 
#-------------------------------------------------------------------------------
#> Handle command line options
fct_doopts $@

#> Run processing
fct_logstash_events
